apiVersion: apps/v1
kind: Deployment
metadata:
  name: i27-helpdesk-auth
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: i27-helpdesk-auth 
  template:
    metadata:
      labels:
        app: i27-helpdesk-auth
    spec:
      containers:
        - name: i27-helpdesk-auth
          image: ${IMAGE_NAME}:${IMAGE_TAG}
          ports:
            - containerPort: 8081
          envFrom:
          - secretRef:
              name: i27-helpdesk-auth-secret
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            failureThreshold: 12
            periodSeconds: 10  
            timeoutSeconds: 3
          resources:
            limits:
              memory: "256Mi"
              cpu: "200m"
            requests:
              memory: "128Mi"
              cpu: "100m"
              # in auth microservice add liveness and readiness probe