apiVersion: v1
kind: Secret
metadata:
  name: i27-helpdesk-auth-secret
stringData:
  SERVER_PORT: 8081
  JWT_EXPIRY_MILLIS: 3600000
  DB_JDBC_URL: "{{DB_JDBC_URL}}" # these values will be coming from jenkins credentials
  DB_USERNAME: "{{DB_USERNAME}}"
  DB_PASSWORD: "{{DB_PASSWORD}}"
  JWT_SECRET: "{{JWT_SECRET}}"


